name: 'Get Domain'
description: 'Determines the API domain based on environment name'

inputs:
  env-name:
    description: 'Environment name (PROD, UAT, TEST, etc.)'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  suffix:
    description: 'Suffix for the subdomain'
    required: true
  api-prefix:
    description: 'Prefix for the subdomain'
    required: false
  

outputs:
  api-subdomain:
    description: 'The determined API domain'
    value: ${{ steps.set-domain.outputs.api_subdomain }}
  subdomain:
    description: 'The determined API domain'
    value: ${{ steps.set-domain.outputs.subdomain }}


runs:
  using: 'composite'
  steps:
    - id: set-domain
      shell: bash
      run: |
        if [ "${{ inputs.env-name }}" = "PROD" ]; then
          if [ -n "${{ inputs.api-prefix }}" ]; then
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=${{ inputs.api-prefix }}.${{ inputs.suffix }}." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=${{ inputs.api-prefix }}." >> $GITHUB_OUTPUT
            fi
          else
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=${{ inputs.suffix }}." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=" >> $GITHUB_OUTPUT
            fi
          fi
          if [ -n "${{ inputs.suffix }}" ]; then  
            echo "subdomain=${{ inputs.suffix }}." >> $GITHUB_OUTPUT
          else
            echo "subdomain=" >> $GITHUB_OUTPUT
          fi
        elif [ "${{ inputs.env-name }}" = "UAT" ]; then
          if [ -n "${{ inputs.api-prefix }}" ]; then
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=${{ inputs.api-prefix }}.${{ inputs.suffix }}.uat." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=${{ inputs.api-prefix }}.uat." >> $GITHUB_OUTPUT
            fi
          else
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=${{ inputs.suffix }}.uat." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=uat." >> $GITHUB_OUTPUT
            fi
          fi
          if [ -n "${{ inputs.suffix }}" ]; then
            echo "subdomain=${{ inputs.suffix }}.uat." >> $GITHUB_OUTPUT
          else
            echo "subdomain=uat." >> $GITHUB_OUTPUT
          fi
        elif [ "${{ inputs.env-name }}" = "TEST" ]; then
          if [ -n "${{ inputs.api-prefix }}" ]; then
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=${{ inputs.api-prefix }}.${{ inputs.suffix }}.test." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=${{ inputs.api-prefix }}.test." >> $GITHUB_OUTPUT
            fi
          else
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=${{ inputs.api-prefix }}.test." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=test" >> $GITHUB_OUTPUT
            fi
          fi
          if [ -n "${{ inputs.suffix }}" ]; then
            echo "subdomain=${{ inputs.suffix }}.test" >> $GITHUB_OUTPUT
          else
            echo "subdomain=test." >> $GITHUB_OUTPUT
          fi
        elif [ "${{ inputs.env-name }}" = "FEATURE" ]; then
          if [ -n "${{ inputs.api-prefix }}" ]; then
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=pr${{ inputs.pr-number }}.${{ inputs.api-prefix }}.${{ inputs.suffix }}.test." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=pr${{ inputs.pr-number }}.${{ inputs.api-prefix }}.test." >> $GITHUB_OUTPUT
            fi
          else
            if [ -n "${{ inputs.suffix }}" ]; then
              echo "api_subdomain=pr${{ inputs.pr-number }}.${{ inputs.suffix }}.test." >> $GITHUB_OUTPUT
            else
              echo "api_subdomain=pr${{ inputs.pr-number }}.test." >> $GITHUB_OUTPUT
            fi
          fi
          if [ -n "${{ inputs.suffix }}" ]; then
            echo "subdomain=pr${{ inputs.pr-number }}.${{ inputs.suffix }}." >> $GITHUB_OUTPUT
          else
            echo "subdomain=pr${{ inputs.pr-number }}." >> $GITHUB_OUTPUT
          fi
        fi 