name: 'Docker Build and Push'
description: 'Builds and pushes Docker images to ECR'

inputs:
  ecr-registry:
    description: 'ECR registry URL'
    required: true
  ecr-repository:
    description: 'ECR repository name'
    required: true
  image-tag:
    description: 'Tag for the Docker image'
    required: true
  env-name:
    description: 'Environment name'
    required: true
  version:
    description: 'Version tag'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build and push Docker image
      shell: bash
      run: |
        docker build -t ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }} -f ${{ inputs.dockerfile-path }} .
        docker push ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }}
        
        if [[ ${{ inputs.env-name }} == PROD ]]; then
          docker tag ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.image-tag }} ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:latest
          docker push ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:latest
        fi 