name: 'Add QuickSight Domain'
description: 'Adds a domain to QuickSight allowed domains list'

inputs:
  domain:
    description: 'Domain to add to QuickSight allowed domains'
    required: true
  aws-region:
    description: 'AWS region for QuickSight'
    required: true
  read-only:
    description: 'If true, only prints the command without executing it'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Add domain to QuickSight
      shell: bash
      run: |
        # Get current allowed domains
        CURRENT_DOMAINS=$(aws quicksight describe-namespace \
          --aws-account-id $(aws sts get-caller-identity --query Account --output text) \
          --namespace default \
          --query 'Namespace.QuicksightNamespaceConfiguration.AllowedDomains[]' \
          --output text)
        
        # Check if domain already exists
        if echo "$CURRENT_DOMAINS" | grep -q "^${{ inputs.domain }}$"; then
          echo "Domain ${{ inputs.domain }} already exists in QuickSight allowed domains"
        else
          echo "Adding ${{ inputs.domain }} to QuickSight allowed domains"
          # Add new domain to existing domains
          UPDATED_DOMAINS="${CURRENT_DOMAINS},${{ inputs.domain }}"
          
          if [ "${{ inputs.read-only }}" = "true" ]; then
            echo "Read-only mode. Command that would be executed:"
            echo "UPDATED_DOMAINS: $UPDATED_DOMAINS"
            echo "aws quicksight update-namespace \
              --aws-account-id $(aws sts get-caller-identity --query Account --output text) \
              --namespace default \
              --region ${{ inputs.aws-region }} \
              --quicksight-namespace-configuration AllowedDomains=${UPDATED_DOMAINS}"
          else
            # Execute the update command
            # aws quicksight update-namespace \
            #   --aws-account-id $(aws sts get-caller-identity --query Account --output text) \
            #   --namespace default \
            #   --region ${{ inputs.aws-region }} \
            #   --quicksight-namespace-configuration AllowedDomains=${UPDATED_DOMAINS}
            echo "Successfully added ${{ inputs.domain }} to QuickSight allowed domains"
          fi
        fi
