name: 'Add QuickSight Domain'
description: 'Adds a domain to QuickSight allowed domains list'

inputs:
  domain:
    description: 'Domain to add to QuickSight allowed domains'
    required: true
  aws-region:
    description: 'AWS region for QuickSight'
    required: true
  read-only:
    description: 'If true, only prints the command without executing it'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Add domain to QuickSight
      shell: bash
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ACCOUNT_ID: $ACCOUNT_ID"

        # Get current namespaces
        NAMESPACES=$(aws quicksight list-namespaces \
          --aws-account-id $ACCOUNT_ID \
          --region ${{ inputs.aws-region }} \
          --query 'Namespaces[].Name' \
          --output text)
        
        CURRENT_DOMAINS=$(aws quicksight describe-account-settings \
          --aws-account-id $ACCOUNT_ID \
          --region ${{ inputs.aws-region }} \
          --query 'AccountSettings.AllowedDomains' \
          --output json | jq -r 'if . == null then "" else join(",") end')
        echo "Found namespaces: $NAMESPACES"
        echo "Current allowed domains: $CURRENT_DOMAINS"
        
        # Check if domain already exists
        if echo "$CURRENT_DOMAINS" | tr ',' '\n' | grep -q "^${{ inputs.domain }}$"; then
          echo "Domain ${{ inputs.domain }} already exists in QuickSight allowed domains"
        else
          echo "Adding ${{ inputs.domain }} to QuickSight allowed domains"
          # Add new domain to existing domains
          if [ -z "$CURRENT_DOMAINS" ]; then
            UPDATED_DOMAINS="${{ inputs.domain }}"
          else
            UPDATED_DOMAINS="${CURRENT_DOMAINS},${{ inputs.domain }}"
          fi
          
          if [ "${{ inputs.read-only }}" = "true" ]; then
            echo "Read-only mode. Command that would be executed:"
            echo "UPDATED_DOMAINS: $UPDATED_DOMAINS"
            echo "            aws quicksight update-account-settings \
              --aws-account-id $ACCOUNT_ID \
              --region ${{ inputs.aws-region }} \
              --allowed-domains ${UPDATED_DOMAINS}"
          else
            # Execute the update command
            # aws quicksight update-account-settings \
            #  --aws-account-id $ACCOUNT_ID \
            #  --region ${{ inputs.aws-region }} \
            #  --allowed-domains ${UPDATED_DOMAINS}
            echo "Successfully added ${{ inputs.domain }} to QuickSight allowed domains"
          fi
        fi
