name: 'Remove QuickSight Domain'
description: 'Removes a domain from QuickSight allowed domains list'

inputs:
  domain:
    description: 'Domain to remove from QuickSight allowed domains'
    required: true
  aws-region:
    description: 'AWS region for QuickSight'
    required: true
    default: 'us-east-1'
  read-only:
    description: 'If true, only prints the command without executing it'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Remove domain from QuickSight
      shell: bash
      run: |
        # Get current allowed domains
        CURRENT_DOMAINS=$(aws quicksight describe-namespace \
          --aws-account-id $(aws sts get-caller-identity --query Account --output text) \
          --namespace default \
          --query 'Namespace.QuicksightNamespaceConfiguration.AllowedDomains[]' \
          --output text)
        
        # Check if domain exists
        if ! echo "$CURRENT_DOMAINS" | grep -q "^${{ inputs.domain }}$"; then
          echo "Domain ${{ inputs.domain }} does not exist in QuickSight allowed domains"
        else
          echo "Removing ${{ inputs.domain }} from QuickSight allowed domains"
          # Remove domain from existing domains
          UPDATED_DOMAINS=$(echo "$CURRENT_DOMAINS" | tr ',' '\n' | grep -v "^${{ inputs.domain }}$" | paste -sd,)
          
          # Create the update command
          # UPDATE_CMD="aws quicksight update-namespace \
          #   --aws-account-id $(aws sts get-caller-identity --query Account --output text) \
          #   --namespace default \
          #   --region ${{ inputs.aws-region }} \
          #   --quicksight-namespace-configuration \"AllowedDomains=${UPDATED_DOMAINS}\""
          
          if [ "${{ inputs.read-only }}" = "true" ]; then
            echo "Read-only mode. Command that would be executed:"
            echo "$UPDATED_DOMAINS"
            # echo "$UPDATE_CMD"
          else
            # Execute the update command
            # eval "$UPDATE_CMD"
            # echo "Successfully removed ${{ inputs.domain }} from QuickSight allowed domains"
          fi
        fi
