name: 'Analyze Terraform Plan'
description: 'Analyzes terraform plan output and extracts summary and changes'

inputs:
  plan-file:
    description: 'The path to the terraform plan file'
    required: true

outputs:
  summary:
    description: 'The plan summary line'
    value: ${{ steps.analyse-tf-plan.outputs.summary }}
  has_changes:
    description: 'Boolean indicating if there are changes'
    value: ${{ steps.analyse-tf-plan.outputs.has_changes }}
  changes:
    description: 'Detailed changes section'
    value: ${{ steps.analyse-tf-plan.outputs.changes }}

runs:
  using: 'composite'
  steps:
    - name: Analyze Plan
      id: analyse-tf-plan
      shell: bash
      run: |
        # Output current directory for debugging
        echo "Current directory: $(pwd)"
        
        # Initialize Terraform to ensure providers are available
        terraform init -input=false
        
        # Save plan output to file
        terraform show ${{ inputs.plan-file }} > plan_output.txt
        
        # Extract the Plan line (with more flexible matching)
        echo 'SUMMARY<<EOF' >> $GITHUB_OUTPUT
        grep -i "^[[:space:]]*plan:" plan_output.txt >> $GITHUB_OUTPUT || echo "No plan summary found"
        echo 'EOF' >> $GITHUB_OUTPUT
        
        # Check for changes
        if grep -q "No changes." plan_output.txt; then 
          echo "has_changes=false"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
        
        # Extract changes section with more reliable markers
        echo 'CHANGES<<EOF' >> $GITHUB_OUTPUT
        sed -n '/Terraform used the selected providers/,/^Plan:/{ /^Plan:/!p }' plan_output.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT